#!/bin/sh
#
# vault - this script manages the vault server
#
# chkconfig:   345 96 04
# processname: vault

### BEGIN INIT INFO
# Provides:       vault
# Required-Start: $local_fs $network
# Required-Stop:  $local_fs $network
# Default-Start: 3 4 5
# Default-Stop:  0 1 2 6
# Short-Description: Manage the vault server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

exec="/usr/sbin/vault"
prog=${exec##*/}

lockfile="/var/lock/subsys/$prog"
pidfile="/var/run/${prog}.pid"
logfile="/var/log/${prog}.log"
sysconfig="/etc/sysconfig/$prog"
confdir="/etc/vault/vault.conf"

[ -f $sysconfig ] && . $sysconfig

start() {
    [ -x $exec ] || exit 5

    echo -n $"Starting $prog: "
    touch $logfile $pidfile
    daemon "{ $exec server $OPTIONS -config=$confdir &>> $logfile & }; echo \$! >| $pidfile"

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        touch $lockfile
        unseal
    fi
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $exec 2>> $logfile
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    echo
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p $pidfile $exec -HUP
    echo
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

unseal() {
    while :
    do
        ss -pl | fgrep "((\"$prog\"," > /dev/null
        [ $? -eq 0 ] && break
        sleep 0.1
    done
    for key in $KEYS; do $exec unseal $CERT $key >> $logfile ; done
}

seal() {
    $exec seal $CERT >> $logfile
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
        ;;
    unseal)
        $1
        ;;
    seal)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|unseal|seal}"
        exit 2
esac

exit $?
